spring.application.name=sds_guesthouse
spring.datasource.url=jdbc:mysql://192.168.50.179:3307/sds_guesthouse
spring.datasource.username=sds
spring.datasource.password=1234

mybatis.mapper-locations=classpath:mapper/*.xml